### ISSUE TITLE
Update maintainers

### ISSUE THREAD

**Issue by kinow** [conda-forge/cylc-flow-feedstock#28]
For the next release, remember to update the maintainers list removing my ID `kinow` :+1: (or before that too, but needs to release a new version/build)

**Comment by hjoliver** [comment]
Here's how to add a maintainer: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

... but there seems to be no "remove user" directive

**Comment by hjoliver** [comment]
The "add user" docs say *Please do not modify this PR or adjust the commit message. This PR is designed to skip building the package.*

Other than avoiding a rebuild, maybe it merely updates the list of maintainers in the recipe:
```yaml
# recipe/meta.yaml
 extra:
    recipe-maintainers: 
     - hjoliver  
     - kinow 
     - oliver-sanders 
```
